### ISSUE TITLE
tie game issue

### ISSUE THREAD

**Issue by tokorokot** [Resike/PVPSound#10]
PVP_MATCH_COMPLETE event returns a number of winner, and at the moment the addon logic for win sounds is like if 0 play sound for horde, else play sound for alliance. So if for example WSG ends with 0:0 the addon plays sound for alliance win. Tie games are rare, so i don't know the return value of PVP_MATCH_COMPLETE for ties

**Comment by Resike** [comment]
We have a sound for ties, maybe we should move that logic here:
`PVPSound:AddToQueue(PS.SoundPackDirectory.."\\"..PS_SoundPackLanguage.."\\GameStatus\\HumiliatingDefeat.mp3")`

My guess it's returning nil on tie matches.

**Comment by tokorokot** [comment]
Hope, one of us will play tie game one day and we' ll discover what value is returning by this event, but nill seems right
