### ISSUE TITLE
I will pay for your gametime if you can update this addon.

### ISSUE THREAD

**Issue by devz3ro** [Resike/PVPSound#2]
This addon is completely broken in v8.X+ of the game (won't load out of date etc.). I will purchase you game time / supply an account if you have time to update. Thanks in advance for your time.

**Comment by stanislavromanov** [comment]
> This addon is completely broken in v8.X+ of the game (won't load out of date etc.). I will purchase you game time / supply an account if you have time to update. Thanks in advance for your time.

Offer still stands? 😂
