### ISSUE TITLE
Multiple POI

### ISSUE THREAD

**Issue by Resike** [Resike/PVPSound#7]
Sometimes the game incorrectly creates 2 different POI for one objective, which could make the addon to spam the same sound over and over again:

![image](https://user-images.githubusercontent.com/3955703/101296157-31c57600-3822-11eb-9c06-b2ad74893a1c.png)

**Comment by tokorokot** [comment]
I've only seen such repeating sound problem in IoC. But It is not clear for me, which POI mistakes results in this error

**Comment by tokorokot** [comment]
I've played about 10 IoCs and this problem didn't occure. So i don't have any idea what can be a reason of this trouble. But i have an idea how to fix it. Normal state for this BG is 13 POIs, and when this trouble occures, there can be 14 (or more?) POIs. Can you please check (i'll also try to do it), what number of POIs will it be on the next AREA_POIS_UPDATED after problem occures. If there will be 13 POIs like in normal state, then the solution is to check POIs number on each AREA_POIS_UPDATED and "break" if number != 13. But if there will be more then 13 POIs all the time until BGs end...i don't know...we need more complicated solution

**Comment by Resike** [comment]
The POI number gets permanently stuck. What happens here I think the game doesn't destroy the object somehow when it's state changes and just creates a new object on top of the existing one. Aka two flags are spawned inside each other. It's kinda rare but annoying.

**Comment by tokorokot** [comment]
Can you please review commit (and pullrequest) with the solution to this issue. I've added a block of code to mark doublePOI objective and don't play sounds for it, but i still can't test it due to this bug rarity
